# Site
title: unTymen
subtitle: "人生无限"
description: ''
keywords:
author: Reid Qian
# language: zh-CN
timezone: ''

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories


# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://untymen.com/
permalink: :year/:month/:day/:hash/
permalink_defaults:
pretty_urls:
  trailing_index: false # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

theme: cactus #typography
## cactus # 
highlight:
  enable: false # we will use the prism plugin instead

plugin:
  - hexo-generator-category-enhance
  - hexo-generator-feed
  - hexo-asset-image
  - hexo-prism-plugin
  - hexo-toc
  - hexo-renderer-marked
  # - hexo-renderer-markdown-it 
  # ... other plugins you'd like to enable

post_asset_folder: true
marked:
  prependRoot: true
  postAsset: true

toc:
  maxDepth: 3

# Generate archive page
archive_generator:
  per_page: 0

# Generate categories index page and each category page
category_generator:
  per_page: 10
  enable_index_page: true

# Generate tags index page and each tag page
tag_generator:
  per_page: 10
  enable_index_page: true

# Generator atom feed for you website
feed:
  type: atom
  path: atom.xml
  limit: 40
  hub:
  content:
  content_limit: 200
  content_limit_delim: ' '

# For syntax highlighting
prism_plugin:
  mode: 'preprocess'
  theme: 'default'
  line_number: true 
